### ISSUE TITLE
code blocks inside tables overlap previous row

### ISSUE THREAD

**Issue by MrGreenTea** [aio-libs/aiohttp-theme#25]
This example reproduces the problem

```rst
+---------------------------+
| one                       |
+---------------------------+
| .. code-block:: python    |
|                           |
|    print("hello")         |
+---------------------------+
```
![image](https://user-images.githubusercontent.com/9407731/100450462-f73b3b00-30b5-11eb-8b0a-8d98a28a0510.png)

**Comment by asvetlov** [comment]
Thanks!
I never pushed multi-line code block inside a table before:)

**Comment by MrGreenTea** [comment]
We're comparing code styles a lot so we use it.
I'm unsure if the best solution would be something like this is the best solution?
```css
:not(td) div[class^="highlight-"] {
    margin-top: -10px;
}
```
