### ISSUE TITLE
No space between caption and the code block in literalinclude

### ISSUE THREAD

**Issue by hoefling** [aio-libs/aiohttp-theme#3]
First of all, this is an awesome theme - I especially like the code highlighting style and the option for custom badges, very cool! The only thing caught my eye is that there's no space separating the caption from the code block when using the `.. literalinclude::` directive. A simple example:

```rst
Hello world:

.. literalinclude:: helloworld.py
   :caption: helloworld.py
```

renders as:

![image](https://user-images.githubusercontent.com/4455652/66828542-92745e00-ef51-11e9-916c-67c4527610a9.png)

To overcome this, ATM I use in a custom CSS:

```css
div.code-block-caption {
    padding: 2px 5px 10px;
}
```
but maybe you can propose a better solution that will benefit everyone.

**Comment by asvetlov** [comment]
Would you propose a pull request?

**Comment by hoefling** [comment]
@asvetlov gladly, although I'm not very familiar with CSS, so not sure whether this is a workaround or a solution.

**Comment by asvetlov** [comment]
The proposal sounds fine
